#!/bin/bash
# Author Swapnil Daingade, Sarjeet Singh
# Script to run inside container to configure maprfs

IP=$(ip addr show eth0 | grep -w inet | awk '{ print $2}' | cut -d "/" -f1)

echo -e "${IP}\t$(hostname -f)\t$(hostname -s) " >> /etc/hosts

mkdir -p /var/mapr
fallocate -l 20G /var/mapr/docker.disk
#dd if=/dev/zero of=/opt/mapr/docker.disk bs=1G count=5

/opt/mapr/server/mruuidgen > /opt/mapr/hostid
cat /opt/mapr/hostid > /opt/mapr/conf/hostid.$$

sed -i 's/AddUdevRules(list/#AddUdevRules(list/' /opt/mapr/server/disksetup

# Add user & group for mapr.
addgroup --gid 500 mapr
adduser --uid 500 --ingroup mapr --disabled-password --gecos "" mapr

# TODO:work-around for zookeeper issue of not starting up.
mkdir -p /opt/mapr/zkdata/version-2
chown mapr.mapr /opt/mapr/zkdata/version-2

touch /opt/mapr/zkdata/zookeeper_server.pid
chown mapr.mapr /opt/mapr/zkdata/zookeeper_server.pid

/opt/mapr/server/configure.sh -C ${IP} -Z ${IP} -D /var/mapr/docker.disk -RM ${IP} --isvm

# Symbolink for libmesos
ln -s /usr/lib/libmesos.so /opt/mapr/hadoop/hadoop-2.7.0/lib/native/libmesos.so

# Make changes to yarn-site.xml & myriad-config-default.yml
tmpYarnSite="/opt/mapr/hadoop/hadoop-2.7.0/etc/hadoop/yarn-site.xml"
tmpMyriadConf="/opt/mapr/myriad/myriad-0.1/conf/myriad-config-default.yml"

# Disable recovery-enabled in yarn-site.xml
matchedLine=`sed -n '10,$ { /yarn.resourcemanager.recovery.enabled/= }' $tmpYarnSite`
nextLine=$((matchedLine+1))
sed -i.bak -e "${nextLine}s/true/false/" $tmpYarnSite

# Modify myriad-config-default.yml
sed -i -e "s/mesosMaster: .*$/mesosMaster: zk:\/\/$ZK_ADDR_EXT\/mesos/" $tmpMyriadConf
sed -i -e "s/zkServers: .*$/zkServers: $ZK_ADDR_EXT/" $tmpMyriadConf
sed -i -e "s/haEnabled: .*$/haEnabled: false/" $tmpMyriadConf

while true
do
sleep 5
done
